config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # get '/users' => 'users#index', as: :user_root # creates user_root_path
  resource :users, only: %i[index show]

  resource :events, only: %i[index show] do
    member do
      get '/show' => 'events#show', as: :participants
      get '/index' => 'events#index', as: :index
      patch '/deregister' => 'events#deregister', as: :deregister
      patch '/register' => 'events#register', as: :register
    end
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root to: 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
# frozen_string_literal: true

# This model deals with Event. An event has many users through participations.
class Event < ApplicationRecord
  has_many :participations
  has_many :users, through: :participations
end

app/models/participation.rb
# frozen_string_literal: true

# This Model is a result of the `has_many_through` in rails. It's a join table
# of users and events table.
class Participation < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
# frozen_string_literal: true

# This Model deals with establishing relations of User with other Models.
# A user has many events through participations
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :participations
  has_many :events, through: :participations
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Default ApplicationController configured to work with devise
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: %I[name email password is_female])
  end

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || index_events_path
  end

  def after_sign_up_path_for(resource)
    stored_location_for(resource) || users_path(resource)
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

# EventsController handles what event details should be visible to who, when
class EventsController < ApplicationController
  include EventsHelper
  include UsersHelper
  include ParticipationsHelper

  def index
    @all_events = Event.all.order(created_at: :desc)
  end

  def show
    @event = Event.find(params[:format])
    _, @participation = participation(current_user, @event)
    @discounted_price = apply_discount(@event) if @participation.present? &&
                                                  discount_eligible?(current_user)
  end

  def deregister
    event = Event.find(params[:format])
    redirect_back(fallback_location: root_path) if redirectable?(event, current_user)

    participation_service, participation = participation(current_user, event)
    participation.discounted_ticket_price = nil
    participation_service.unattend_event(participation)
    redirect_back(fallback_location: root_path)
  end

  def register
    event = Event.find(params[:format])
    redirect_back(fallback_location: root_path) if redirectable?(event, current_user)

    participation_service, participation = participation(current_user, event)
    participation.discounted_ticket_price = participation_service.price_after_discount if discount_eligible?(current_user)
    participation_service.attend_event(participation)
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    gender = params['user']['is_female']
    params['user']['is_female'] = gender == 'Female'
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /users/sign_in
  def create
    super
  end

  # DELETE /users/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/events_helper.rb
# frozen_string_literal: true

# This is an EventsHelper Module to deal with events related calculations
module EventsHelper
  def apply_discount(event)
    Discount.discounted_price(event.ticket_fee, 5)
  end

  def show_price(event, user)
    if user.is_female?
      "Attend for discounted ticket fee: #{price_after_discount(event)}"
    else
      "Attend for ticket fee: #{event.ticket_fee}"
    end
  end

  def price_after_discount(event)
    event.ticket_fee - apply_discount(event)
  end

  def event_attendable?(event)
    event.event_date.in_time_zone.utc > DateTime.now.in_time_zone.utc
  end
end

app/helpers/participations_helper.rb
# frozen_string_literal: true

# This is a ParticipationsHelper Module to deal with participations related operations
module ParticipationsHelper
  def participation(user, event)
    return nil if user.blank? || event.blank?

    participation_service = ParticipationService.new(user, event)
    [participation_service, participation_service.handle_event_participation]
  end

  def redirectable?(event, user)
    event.blank? && user.blank?
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

# This is a UsersHelper Module to deal with users related operations
module UsersHelper
  def attending_event?(user, event, participation)
    user&.events.present? &&
      user.events.include?(event) &&
      participation&.attending.present?
  end

  def discount_eligible?(user)
    user.is_female?
  end
end

app/views/events/index.html.erb
<div class="container">
  <div class="row">
    <div class="event-box">
      <br/>
      <h1>Events</h1>
      <br/>
      <table class="table table-bordered table-hover">
        <thead>
          <tr>
            <th>Name</th>
            <th>Date</th>
            <th>Ticket Fee</th>
            <% if current_user.present?%>
              <th>Attend/Unattend</th>
            <% end %>
            <th>Participants</th>
          </tr>
        </thead>
        <tbody>
          <% @all_events.each do |event| %>
            <tr>
              <td><%= event.name =%></td>
              <td><%= event.event_date =%></td>
              <td><%= event.ticket_fee =%></td>
              <%if current_user.present?%>
                <td>
                  <div class="container">
                    <% _, participation = participation(current_user, event) %>
                    <%= render 'shared/event_attendance', event: event , participation: participation%>
                  </div>
                </td>
              <% end %>
              <div class="actions">
                <td><%= link_to "View Users", participants_events_path(event), class: 'btn btn-primary btn-sm'%></td>
              </div>
            </tr>
          <% end %>
        </tbody>
      </table>
      <br>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<html>
  <body>
    <br/>
    <br/>
    <div class="event-box">
      <div class="container">
        <%= render 'shared/event_attendance', event: @event , participation: @participation %>
      </div>
      <br/>
      <br/>
      <table class="table table-bordered table-hover" border="1" cellspacing>
        <thead>
          <tr>
            <th>Name</th>
            <th>Gender</th>
          </tr>
        </thead>
        <tbody>
          <% @event.users.each do |user| %>
            <% next if user == current_user%>
            <tr>
              <td><%= user.name =%></td>
              <td><%= user.is_female? ? 'Female' : 'Male' =%></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <br>
    </div>
  </body>
</html>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to "Demo App", root_path, class: 'navbar-brand' %>
        </div>

        <div class="collapse navbar-collapse" id="navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to 'Posts', '#' %></li>
                <% if current_user %>
                    <li><%= link_to 'Edit Profile',edit_user_registration_path %></li>
                    <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
                <% else %>
                    <li><%= link_to 'Login', new_user_session_path %></li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tiket</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%=render 'shared/navbar'%>
    <div class="container">
      <%= yield %>
    </div>
    <% if flash.any? %>
      <%=render 'shared/toaster'%>
    <% end %>
  </body>
</html>

app/views/shared/_devisemes.html.erb
<% if defined?(resource) and resource.errors.any? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |m| %>
      toastr.error('<%= m %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_event_attendance.html.erb
<% if event_attendable?(event) %>
  <% if attending_event?(current_user, event, participation) %>
    <%= form_for event, :url => deregister_events_path(event) do |f| %>
      <%= f.submit 'Unattend', class: 'btn btn-danger' %>
    <% end %>
  <% elsif current_user.present? %>
    <%= form_for event, :url => register_events_path(event) do |f| %>
      <%= f.submit show_price(event, current_user), class: 'btn btn-success btn-sm' %>
    <% end %>
  <% end %>
<% else %>
  <%= button_to 'Event Expired' , {}, :disabled => true %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-md-auto">
        <div class="tiket-text-logo">
          <h1> &nbsp;Tiket!&nbsp;</h1>
        </div>
      </ul>
      <ul class="navbar-nav ml-md-auto">
        <li class="nav-item">
          <%= render 'devise/menu/home_items' %>
        </li>
        <li class="nav-item">
          <%= render 'devise/menu/login_items' %>
        </li>
        <li class="nav-item">
          <%= render 'devise/menu/registration_items' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_toaster.html.erb
<script type="text/javascript">
  <% flash.each do |key, value| %>
  <% type = key.to_s.gsub("alert", "error").gsub("notice", "success") %>
    toastr.<%= type %>("<%= value %>");
  <% end %>
</script>